### ISSUE TITLE
Start to correct homepage.html pics and text

### ISSUE THREAD

**Issue by jdhtwo** [mattcroce/HSver1#21]

**Comment by jdhtwo** [comment]
All pics and text have been updated to be "professional", as opposed to the big pic of Matt and the carousel slider of poop! Obviously a work in progress, but this is now appropriate for the public to view.

**Comment by mattcroce** [comment]
Sweeeet. I'll check it out when I'm home on my local machine and can easily view the changes

**Comment by jdhtwo** [comment]
Let me know what you think. If it's good for now, let me be the one to throw it in Bluehost - I'm looking to gain experience points!

**Comment by mattcroce** [comment]
will do - i'll take a look at some point tonight, probably late-ish.

+25 XP!
