### ISSUE TITLE
Create a new SQL database table for Savisky Model

### ISSUE THREAD

**Issue by jdhtwo** [mattcroce/HSver1#4]
Under the project heading of #2

**Comment by jdhtwo** [comment]
Savisky_Model db was created in Bluehost phpMyAdmin reflecting the data entry info in [savisky-model-1.php](https://github.com/mattcroce/HSver1/blob/master/savisky-model-1.php)

**Comment by mattcroce** [comment]
created hstype2 db and added example user with all rights to db

**Comment by mattcroce** [comment]
woops, looks like we're doing things at the same time

**Comment by jdhtwo** [comment]
OH SNAP
