### ISSUE TITLE
Folder menu icon does not appear when page is not full screen

### ISSUE THREAD

**Issue by jdhtwo** [mattcroce/HSver1#49]
Index/Home and Clients work fine.

About, Learn More, Contact need to be fixed.

**Comment by jdhtwo** [comment]
Works fine on my local machine. Not working as uploaded to Bluehost.

**Comment by jdhtwo** [comment]
For the record, I have no idea how I actually fixed this, but I did.

**Comment by mattcroce** [comment]
Ha! This just made me laugh out loud at my desk. well done!

**Comment by jdhtwo** [comment]
:)
